### ISSUE TITLE
Repository Permissions

### ISSUE THREAD

**Issue by ArashTheKID** [zahiar/terraform-provider-bitbucket#111]
Hi,
as of May 19th 2022, you can set repository permissions per REST API for users and groups. I see the implementation for the groups, are there any plans to add the users as well? In general, in REST API references under repository are a lot more settings than already implemented in your provider. It would be very nice and convenient, if you could please implement them as well.
Cheers and Thanks
A.

**Comment by zahiar** [comment]
Thanks for letting me know about that 👍 

I've created a ticket in the underlying go-bitbucket that's used in the provider: https://github.com/ktrysmt/go-bitbucket/issues/213

**Comment by zahiar** [comment]
@ArashTheKID version 1.2.0 has been released that adds a new resource & datasource for managing user permissions on repositories. As well as migrating group permissions over to Bitbucket's REST API v2.0.

Please give it a go and provide any feedback 🙂
