### ISSUE TITLE
Feature Request: Resource for Pipeline SSH key

### ISSUE THREAD

**Issue by stephan242** [zahiar/terraform-provider-bitbucket#113]
I've got a feature request:

In a Bitbucket repo under Settings > Pipelines > SSH Keys one can create or import an SSH key pair which can then be used to authenticate via SSH in a pipeline container. Could this be added as a resource at all? Or potentially be added to the `bitbucket_repository` resource? While at it, maybe also the "Known Hosts" configurable there.

**Comment by zahiar** [comment]
@stephan242 Would the deploy key resource be of use here?
https://registry.terraform.io/providers/zahiar/bitbucket/latest/docs/resources/bitbucket_deploy_key

**Comment by PierrickPuimeanChieze** [comment]
@zahiar I have the same request, and the requested SSH key is not a deploy key. Deploy key is SSH key allowing external server to access your repository.
The requested key is the one which allow pipeline to identify on an external server. It can be retrieved using the API here : https://developer.atlassian.com/cloud/bitbucket/rest/api-group-pipelines/#api-repositories-workspace-repo-slug-pipelines-config-ssh-key-pair-get

It would be nice to have access to this information at least as a data resource.

Here at little use case which may help you to understand the request : 
I have a module which allow me to create multiple environments for my application : test, prod, client-specific, etc.
For each environment : 
* I create a VM on a cloud provider.
* I create an environment on bitbucket
* I create a new bitbucket pipeline job for deploying my application to the newly created VM, using ssh and the newly created deployment environment.

But for the last step to work, I need to be able to provide the VM with the SSH key used for identify pipeline environment.

Hoping that will help you.

And thanks for your work.

**Comment by zahiar** [comment]
Thanks for the link - I've submitted a pull request into the go-bitbucket module this provider uses, once that's approved & merged in, I can push up my changes to get it added into the Terraform Provider 🙂 

https://github.com/ktrysmt/go-bitbucket/pull/221
