### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by twoodhouse** [zahiar/terraform-provider-bitbucket#184]
Hi @zahiar, could you please add a license to this repository so people can legally fork it?

Maybe one like this other bitbucket terraform provider here: https://github.com/DrFaust92/terraform-provider-bitbucket/blob/master/LICENSE.
Up to you, of course.

Thank you! Should be a quick change.

**Comment by zahiar** [comment]
Done 🙂

**Comment by twoodhouse** [comment]
Thank you!!
