### ISSUE TITLE
Provide a more convenient way to look up users

### ISSUE THREAD

**Issue by markti** [zahiar/terraform-provider-bitbucket#67]
The UUID is not a very easily accessible piece of data. It would be much easier to add default reviewers if we could use a more easily shared / maintained piece of information about a user like their username / email address.

```
data "bitbucket_user" "example" {
  nickname = "the-dude"
}
```

```
data "bitbucket_user" "example" {
  email = "the-dude@acme.com"
}
```

**Comment by zahiar** [comment]
Yeah I know it's not great 😞 , looking at Bitbucket's API documentation, they don't appear to support that.
https://developer.atlassian.com/cloud/bitbucket/rest/api-group-users/#api-users-selected-user-get

**Comment by kevinduterne** [comment]
We created a script to call a different api to get all members in the account and then create a user map off of that. Maybe this logic can help you 

`#!/bin/sh

WS=workspacename
COUNT=0
I=1
JSON1="[]"
JSON2="[]" # the value when page is exceeded, so COUNT will equal 2

until [ $COUNT -eq 2 ]; do
	# shellcheck disable=SC2039,SC2046,SC2086
	JSON2=$(curl --silent --location --request GET "https://api.bitbucket.org/2.0/workspaces/$WS/members?page=$I" --header 'Accept: application/json' --header 'Authorization: Basic '$(echo -n $BITBUCKET_USERNAME:$BITBUCKET_PASSWORD | base64) | jq '[.values[].user | {uuid: .uuid, nickname: .nickname, display_name: .display_name}]')
	COUNT=${#JSON2}
	I=$((I + 1))
	JSON1=$(jq --argjson arr1 "$JSON1" --argjson arr2 "$JSON2" -n '$arr2 + $arr1')
done

echo "$JSON1" | jq 'reduce .[] as $i ({}; .[$i.display_name] = $i.uuid)'
`

Then we use this script as a data provider to be able to get a map of users
`data "external" "bitbucket_users" {
  program = ["bash", "${path.root}/bitbucket_users.sh"]
}`

**Comment by zahiar** [comment]
I've been experimenting with @kevinduterne approach above but within the provider itself, so a new resource like:
```
data "bitbucket_user_team_member" "user" {
  nickname = "my-user"
  workspace = data.bitbucket_workspace.this.id
}
```

This will return all the same attributes as data source `user` - reason for new reason is due to me needing to add a new required argument `workspace`. It kinda works for my account of 1 user 😂 so no idea how it will work for an actual larger account.

But first, waiting on some upstream pull requests to get merged in before I add this as an experimental data source into the provider, hopefully get some feedback before removing the _experimental_ label later on.

**Comment by zahiar** [comment]
Upstream pull request has been merged: https://github.com/ktrysmt/go-bitbucket/pull/196

**Comment by zahiar** [comment]
@markti @kevinduterne what are your thoughts on this pull request? Does this help make things easier, assuming it all works fine, will need your help on testing it out on large teams 🙂 
https://github.com/zahiar/terraform-provider-bitbucket/pull/94

**Comment by zahiar** [comment]
Keeping this open for now so any feedback can be provided on the new experimental `bitbucket_user_workspace` data source.
