### ISSUE TITLE
Branch Permission Restriction: check the last commit for at least X successful build and no failed builds

### ISSUE THREAD

**Issue by markti** [zahiar/terraform-provider-bitbucket#69]
bitbucket_branch_restriction does not seem to support the following branch restriction:

check the last commit for at least X successful build and no failed builds

![image](https://user-images.githubusercontent.com/3155241/149992913-b116e17c-3838-4724-b7af-37db75d935cd.png)

**Comment by zahiar** [comment]
Hi @markti, try using `require_passing_builds_to_merge` - that should work.

```
resource "bitbucket_branch_restriction" "test" {
  workspace  = ...
  repository = ...
  pattern    = ...
  kind       = "require_passing_builds_to_merge"
  value      = 1
}
```
